daysUntilStale: 60
daysUntilClose: false
exemptLabels:
  - pinned
  - security
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity (this bot only works as a reminder, it will not close issues).
closeComment: false
