(source gnu)
(source melpa)

(package-file "src/elisp/treemacs.el")

(development
 (depends-on "dash")
 (depends-on "f")
 (depends-on "s")
 (depends-on "ht")
 (depends-on "ace-window")
 (depends-on "all-the-icons")
 (depends-on "pfuture")
 (depends-on "hydra")
 (depends-on "evil")
 (depends-on "projectile")
 (depends-on "magit")
 (depends-on "persp-mode")
 (depends-on "perspective")
 (depends-on "with-editor")
 (depends-on "buttercup")
 (depends-on "el-mock")
 (depends-on "ert-runner"))
